#!/bin/sh

#
# Work around bugs in mypy by filtering out false positive error messages.
#

set -e
set -u

tmp="$(mktemp -t mypy.XXXX)";

# Bugs filed:
# Callable has no attribute "todo": ... uh, not sure that's a bug, but ...
# Too many arguments for: https://github.com/python/mypy/issues/20

mypy "$@"                                                                                          \
    | grep -v                                                                                      \
        -e ": error: Cannot find module named 'arrow.parser'"                                      \
        -e ": error: Cannot find module named 'cattr'"                                             \
        -e ": error: Cannot find module named 'docker.[^']*'"                                      \
        -e ": error: Cannot find module named 'hyperlink'"                                         \
        -e ": error: Cannot find module named 'hypothesis'"                                        \
        -e ": error: Cannot find module named 'hypothesis.[^']*'"                                  \
        -e ": error: Cannot find module named 'klein'"                                             \
        -e ": error: Cannot find module named 'klein.[^']*'"                                       \
        -e ": error: Cannot find module named 'twisted'"                                       \
        -e ": error: Cannot find module named 'twisted.[^']*'"                                       \
        -e ": error: No library stub file for "                                                    \
        -e ': error: "Callable\[\[[^\]\+\], None\]" has no attribute "todo"'                       \
        -e ': error: <nothing> has no attribute "__iter__"'                                        \
        -e ': error: Argument 1 to "instance_of" has incompatible type "Type\[Iterable\[Any\]\]"'  \
        -e ': error: Too many arguments for "fget" of "property"'                                  \
        -e ': error: Unsupported left operand type for '                                           \
        -e ': note: '                                                                              \
        -e '^src/ims/ext/.*sqlite.py:[0-9:]\+: error: .* incompatible with supertype ".\+"' \
        -e '^src/ims/ext/.*sqlite.py:[0-9:]\+: error: Unexpected keyword argument "lines" for "QueryPlanExplanation"' \
        -e '^src/ims/ext/enum.py:[0-9:]\+: error: Cannot assign to a method' \
        -e '^src/ims/ext/sqlite.py:[0-9:]\+: error: Unexpected keyword argument "factory" for "cursor" of "Connection"' \
        -e '^src/ims/model/json/_ranger.py:[0-9:]\+: error: Incompatible types in assignment ' \
        -e '^src/ims/store/.*/_queries.py:[0-9:]\+: error: Unexpected keyword argument "[^"]*" for "Queries"' \
        -e 'src/ims/ext/enum.py:[0-9:]\+: error: Self argument missing for a non-static method (or an invalid type for self)' \
        -e 'src/ims/ext/enum.py:[0-9:]\+: error: Signature of "_generate_next_value_" incompatible with supertype "Enum"' \
        -e 'src/ims/model/json/_type.py:[0-9:]\+: error: Incompatible types in assignment (expression has type "Type\[str\]", base class "Enum" defined the type as "str")' \
        > "${tmp}" || true;

sort < "${tmp}";

if grep -e ": error: " "${tmp}" > /dev/null; then
    exit 1;
fi;
